name: Update Markdown Document

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  update-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: List repository files
        run: ls -la

      - name: Generate Documentation
        env:
          API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          pip install google-genai
          pip install sentence-transformers
          pip install numpy

          python update_word.py

      - name: Commit updated document
        run: |
          git config user.email "omkarsubhashghongade21@gmail.com"
          git config user.name "omkar_ghongade"
          git add demo.md
          # Commit the changes with a message
          git commit -m "Update document with new changes"
          git push

      - name: Check for previous commit message
        run: |
          echo "Previous commit message: ${{ github.event.head_commit.message }}"
