name: Update Markdown Document

on:
  push:
    branches: [ main ]  # Adjust if you want to run on different branches

jobs:
  update-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: List repository files
        run: ls -la

      - name: Update Markdown Document
        run: |
          # Run your Python script and pass the commit message as an argument
          python update_word.py "${{ github.event.head_commit.message }}"

      - name: Commit updated document
        run: |
          # Configure Git
          git config user.email "omkarsubhashghongade21@gmail.com"
          git config user.name "omkar_ghongade"
          # Add the updated Markdown file (update the path if necessary)
          git add demo.md
          # Commit the changes with a message that includes the commit message
          git commit -m "Update document with commit message: ${{ github.event.head_commit.message }}"
          git push
